FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libsqlite3-dev \
    && docker-php-ext-install pdo pdo_sqlite
    
RUN a2enmod rewrite

COPY --chown=www-data:www-data backend/ /var/www/html
COPY --chown=www-data:www-data app/dist/. /var/www/html/public
COPY --chown=www-data:www-data backend/apache-config.conf /etc/apache2/sites-available/000-default.conf

USER www-data
WORKDIR /var/www/html/
CMD ["./run-script.sh"]