networks:
  hit-the-note-network:
    driver: bridge
    name: hit-the-note-network

services:
  backend:
    build: ./backend
    container_name: hit-the-note-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/database:/var/www/html/database
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    working_dir: /var/www/html
    networks:
      - hit-the-note-network

  application:
    build: ./app
    container_name: hit-the-note-app
    ports:
      - "3000:5173"
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host"
    networks:
      - hit-the-note-network
